site_name: COMP423 Course Notes

theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
  icon:
    admonition:
      note: material/note
      tip: material/lightbulb-on
      warning: material/alert
      danger: material/alert-circle
      question: material/help-circle

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences